### PR TITLE
SITES-753: Change authorizations to OR from AND.

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Changes the authorization restrictions to be additive
- This changes the behavior of the module but I think it better aligns with UX.

# Needed By (Date)
- For GUP Launch

# Urgency
- med-hi

# Steps to Test

1. Clone gup to local
2. Try logging in without your sunet id in the allowed sunets
3. Get denied
4. Check out this branch
5. Log in 
6. Have access

# Affected Projects or Products
- Everything on SAML

# Associated Issues and/or People
- SITES-753
- SITES-993

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by pookmish** [comment]
any suggestions on how to clone?

**Comment by sherakama** [comment]
```
drush @acsf.dev.cardinald7.gup sql-dump > gup.sql
lando db-import gup.sql

or 
drush sql-sync @acsf.dev.cardinald7.gup @self

and
drush rsync @acsf.dev.cardinald7.gup:%files @self
```

**Comment by jbickar** [comment]
I ratified the UX of this choice with David. There are other issues with the UX of authorizations and this form, but this is the correct decision here.

**Comment by sherakama** [comment]
It is the port numbers that are throwing you off. Something about my original attempts at this local setup had issues with port number. Let me see what I have in my config to rectify this.

**Comment by jbickar** [comment]
It's weird, it was working before.

**Comment by sherakama** [comment]
Hmmm yeah. Looks like your url is in the trusted domains
```
$config['trusted.url.domains'] = array(
  'cardinald7.sws:443',
  'cardinald7.sws:80',
  'cardinald7.sws',
  'cardinald7.lndo.site:443',
  'cardinald7.lndo.site:80',
  'cardinald7.lndo.site',
);
```

**Comment by sherakama** [comment]
In your local.settings.php file are you using the `cardinald7` authsource?

`$conf['stanford_simplesamlphp_auth_authsource'] = "cardinald7";`

**Comment by jbickar** [comment]
```
// Local path to simpesamlphp.
$conf['stanford_simplesamlphp_auth_installdir'] = "/app/simplesamlphp";
// The SP for local development.
$conf['stanford_simplesamlphp_auth_authsource'] = "cardinald7";
// Force https for the sake of SAML auth.
$conf['stanford_ssp_force_https'] = TRUE;
```

**Pull request merged**
