### PR TITLE
SITES-725: Found another avenue where destination was missing.

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Adds a destination parameter to the login block link.

# Needed By (Date)
- Meh

# Urgency
- Low

# Steps to Test

1. Check out this branch
2. Navigate to an interior page as an anonymous user
3. Click on the login link on the top right of the screen
4. Be logged in and back on to the page you were just at

# Affected Projects or Products
- Everything

# Associated Issues and/or People
- SITES-725

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jbickar** [comment]
Is this the same issue in https://stanfordits.atlassian.net/browse/SITES-745?

**Comment by jbickar** [comment]
@sherakama you good with my changes?

**Comment by sherakama** [comment]
@jbickar The long form of the array syntax is not the recommended syntax style.

Please see:
https://www.drupal.org/docs/develop/standards/coding-standards#array

**Comment by sherakama** [comment]
For readability, you may separate the nested arrays into multiple lines.

**Comment by jbickar** [comment]
Huh. I learned something today.

Don't let it happen again.

**Comment by jbickar** [comment]
I'm not a big fan of that, but OK, it's hard to argue with official coding standards.

**Comment by jbickar** [comment]
How about now?

**Comment by sherakama** [comment]
Looks good to me.

Tank yew.

**Comment by jbickar** [comment]
`SITES-725` was a typo. `SITES-745` is the actual JIRA issue.

That mistake shall die with this PR.

**Pull request merged**
