### PR TITLE
SITES-216: Updated validation logic to split user from local and saml…

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Updates the allow login logic to separate checks from local and saml

# Needed By (Date)
- End of sprint?

# Urgency
- Low

# Steps to Test

1. Check out this branch on a test site
2. Add restrictions to both local and saml users at /admin/config/stanford/stanford_ssp/authorizations
3. Authenticate with a local user that has valid credentials and not
4. Authenticate with a saml user that has valid credentials and not

# Affected Projects or Products
- SITES 2.0

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jbickar** [comment]
Thanks for tackling this; this PR might get pushed to the next sprint.

We should start using more sports metaphors...

**Comment by sherakama** [comment]
It was a team effort. The top players had to be the top players and put out 110% in order to get this win. If it wasn't for everyone in the scrum pushing the ball down the field we wouldn't have hit that basket.

**Comment by sherakama** [comment]
https://www.youtube.com/watch?v=KfU69_up02Y

**Comment by jbickar** [comment]
Big players make big plays in big games.

If you don't make big plays in big games, you're not a big player.

**Comment by jbickar** [comment]
This branch resolves the issue in testing on Anchorage. Now for reading the code.

**Comment by sherakama** [comment]
Yes, that sounds accurate. 
The error in the logic before was that it never separated the checks from the local users with the saml based users and entire code blocks were skipped. No new functionality was added nor was anything removed. A refactor to allow for the separation of this logic is all.

**Comment by jbickar** [comment]
You reared back with all you had on this one and threw a strike straight over the heart of the plate. I mean, it really split the uprights, an uppercut knockout punch right on the chin. This was back-of-the-net, a swish from downtown, a Gordie Howe hat trick.

Do we need to worry about the Code Climate errors?

**Comment by sherakama** [comment]
The long variable name and missing period on the inline comment are not show stoppers but something I probably should have fixed as it was low hanging fruit.

**Comment by jbickar** [comment]
We're switching from sports to agriculture metaphors now?



On Dec 8, 2017, at 09:22, Sherakama <notifications@github.com<mailto:notifications@github.com>> wrote:


The long variable name and missing period on the inline comment are not show stoppers but something I probably should have fixed as it was low hanging fruit.

**Pull request merged**
