### PR TITLE
Stanford SSP / SSO / SimpleSAML integration

### PR DESCRIPTION
**Pull request by sherakama**
# Ready for Review

INSTALLATION (if you have simplesaml php running locally):
* Build a JSA/JSV website using 5.x anchorage build
* disable and uninstall stanford_ssp
* enable stanford_ssp and stanford_saml_block

I will also build out a test on: https://hsdo167.anchorage.stanford.edu/

REVIEW:
Please confirm the user stories in the following tickets
- https://stanfordits.atlassian.net/browse/HSDO-276
- https://stanfordits.atlassian.net/browse/HSDO-277
- https://stanfordits.atlassian.net/browse/HSDO-278
- https://stanfordits.atlassian.net/browse/HSDO-283
- https://stanfordits.atlassian.net/browse/HSDO-285
- https://stanfordits.atlassian.net/browse/HSDO-286
- https://stanfordits.atlassian.net/browse/HSDO-351

Please add comments to the tickets where you find bugs, incomplete work, or items that are just down right not right.

### CODE REVIEW

**Comment by jbickar** [comment]
w00t.

**Comment by jbickar** [comment]
Whoa, you can assign two people to a PR? Crazy talk.

**Comment by sherakama** [comment]
> On Jun 10, 2016, at 5:43 PM, John Bickar <notifications@github.com> wrote:
> 
> Whoa, you can assign two people to a PR? Crazy talk.
> 
I know, that's my brother, Crazy Talk. We're all a little worried about him.

**Comment by sherakama** [comment]
https://hsdo167.anchorage.stanford.edu/ has been built for testing purposes.

**Comment by sherakama** [comment]
Moving to 2.x

**Pull request closed without merging**
